### PR TITLE
add move start event

### PR DESCRIPTION
**Pull request by hussam-i-am**
### Description

This adds a new event that will be triggered when a user being moving an item by clicking and dragging the handle. 

### Reason

For styling purposes, I would like to display the `grab/grabbing` cursors while dragging an item. `grab` is simple enough:

```
  .drag-handle {
    cursor: grab;
  }
```

But it seems `grabbing` is not as straight-forward. When dragging begins, we are no longer over the actual handle or item, so targeting the `is-dragging` class will not work. By adding an event to be triggered when dragging begins, one solution could be to add a class like `is-dragging` to the `body` tag, allowing us to always display the `grabbing` cursor in that case:

```
  body.is-dragging,
  body.is-dragging * {
    cursor: grabbing !important;
    cursor: -moz-grabbing !important;
    cursor: -webkit-grabbing !important;
  }
```

Introducing this event seems to make sense, to pair with the existing `task-lists-move` event. I called the new one `task-lists-move-start` and considered renaming `task-lists-move` to `task-lists-move-end` to make it a bit more consistent and clear, but kept it as is to avoid breaking changes. 

### Code Changes
- Adds the `task-lists-move-start` event to be dispatched when `dragstart` is triggered
- Updates `SortEndArgs` interface to be more generic and shared by both `task-lists-move` and `task-lists-move-start`
- Adds test for both events

### CODE REVIEW

**Comment by hussam-i-am** [comment]
guess I did not think this through since `task-lists-move` would not be dispatched if no item was actually moved, so would need either another event, or consider just listening directly to the `dragstart`/`dragend` events in the code using `<task-lists>`

**Comment by smockle** [comment]
> listening directly to the `dragstart`/`dragend` events in the code using `<task-lists>`

I’ve implemented this approach before 👍 (can share details elsewhere, if you’re interested)

**Comment by lukewar** [comment]
@hussam-i-am should we close this one then?

**Comment by hussam-i-am** [comment]
Yeah, might as well. May create a separate PR to add the tests I wrote that still apply 😅

**Pull request closed without merging**
